### ISSUE TITLE
Make members in a space searchable

### ISSUE THREAD

**Issue by SeanTMartin** [soonlabs/soonaverse-dao#133] opened 2021-12-06 03:24 UTC
**Is your feature request related to a problem? Please describe.**
You cannot go to a space and look up a member. This is necessary for the purposes of granting guardianship to a member in a large DAO for example.

**Describe the solution you'd like**
There should be a search bar in a space that allows me to find a member

**Describe alternatives you've considered**
I got nothing

**Comment by adamkundrat** [comment] 2021-12-06 03:43
Yes this is on our backlog and completely agree we need to get this done very soon.

**Comment by adamkundrat** [comment] 2021-12-06 05:44
@frnfa - can you add me the search box pls

**Comment by adamkundrat** [comment] 2021-12-07 17:12
duplicate of #71

**Closed by adamkundrat** 2021-12-07 17:12 UTC
Labels: enhancement
