### ISSUE TITLE
Search doesn't work properly, can't search for numbers

### ISSUE THREAD

**Issue by Ronaldvdb** [soonlabs/soonaverse-dao#609] opened 2022-04-08 11:53 UTC
When I want to find NF3 set #93 and I SIMPLY type 93 in search, it doesn't respond...

Please see the importance of this. It's easy to fix.

People are not willing to scroll down for AGES to HOPEFULLY find their NFT. I know there is a dedicated page with all data about the NF3s. But it can only be found if you ask for that link in discord..... and the DISCORD LINK IN SOONAVERSE DOCS DOESN'T EVEN WORK.

Main priority is to save time of your customers. This is the most precious thing in life and business. It keeps the flow going and people will remember unconsciously that Soonaverse is a smooth ride. This will trigger return customers. Perhaps shorter, but WAY more productive, efficient and profitable.

**Comment by adamkundrat** [comment] 2022-04-09 15:17
Closing as duplicate of #220 . It’ll be fixed there.

**Closed by adamkundrat** 2022-04-09 15:17 UTC
Labels: bug
