### ISSUE TITLE
'Contributes To' in the Personal Profile seems to contain a random selection of Spaces

### ISSUE THREAD

**Issue by dumdave** [soonlabs/soonaverse-dao#164] opened 2021-12-07 17:57 UTC
**Describe the bug**
I belong to Spaces that are not listed, and have earned badges (e.g. in the DeFi Academy Space 500 points) but that Space is not listed here.

**Comment by adamkundrat** [comment] 2021-12-07 18:04
This view here is limited to only 6 spaces. Now having so much more data in the system we have to think how we improve the UI. We need add show all function. See issue #68 

We'll try to get this into 0.2 milestone: https://github.com/soonlabs/soonaverse-dao/milestone/2

duplicate of #68

**Closed** 2021-12-07 18:04 UTC
