### ISSUE TITLE
improve "back to discover" function

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#171] opened 2021-12-07 23:34 UTC
if you scroll down in the "spaces" and enter a space to check it out, the "back to discover button" brings you back to the start of the spaces page.
Would be better to go back to the place where you have been before in your scrolling

**Comment by adamkundrat** [comment] 2021-12-08 03:59
Agree, duplicate of #149. We will close it as part of that issue.

**Closed by adamkundrat** 2021-12-08 03:59 UTC
