### ISSUE TITLE
Transfer an NFT

### ISSUE THREAD

**Issue by iotaholics** [soonlabs/soonaverse-dao#642] opened 2022-04-16 15:28 UTC
**Describe the bug**
I am from the collection IOTAHOLICS.
I am transferring the NFTs to the giveaway winners and when I want to put the name in "Specific member(s) only (Transfer)" there are a couple of accounts that do not appear.

**To Reproduce**
1. Go to 'Your NFT'
2. Click on 'Sell NFT'
3. Click on 'Fixed price'
4. Scroll down to 'Specific member(s) only (Transfer)'
5. Write  'IOTA方可 (IOTA without the kanji characters is an other user)'
6. Write 'iot'
7. See error

**Expected behavior**
Write the nickname of the person in 'Specific member(s) only (Transfer) and be able to assign him/her the NFT

**Screenshots**
![imagen](https://user-images.githubusercontent.com/103837394/163680340-33f94e51-f80a-4405-9921-29295d9af257.png)
![imagen](https://user-images.githubusercontent.com/103837394/163680528-53fde8cf-2fe4-49bc-bca3-99e3978701ec.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment] 2022-04-18 15:36
duplicate of https://github.com/soonlabs/soonaverse-dao/issues/531

**Closed by adamunchained** 2022-04-18 15:36 UTC
Labels: bug
