### ISSUE TITLE
Improve Search Bar

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#292] opened 2022-02-22 11:39 UTC
I know is not related to the Marketplace, but I've noticed that the main search bar in the 'Disvovery Screen' doesn't work as efficient as the search bars in other places like for example in 'Profile'. If I want to search the IOTA DAO Pioneers, in the former (first image) I cannot find it that easily (while in the later (second image) I can) and when theres' so many Spaces and/or members it's a bit annoying from the user's perspective. Can you check it? 

![image](https://user-images.githubusercontent.com/100204340/155124525-c031fdc8-5061-4fda-8a4d-5a196bcc9828.png)

![image](https://user-images.githubusercontent.com/100204340/155124581-740c0cd7-8c9c-4733-b041-d41c7e734654.png)

**Comment by adamkundrat** [comment] 2022-02-22 15:31
We hate our searching. Its a big problem, I agree. We have got a plan to improve it but right now its just pushed down the backlog. I see us looking at this during March/April

**Comment by adamkundrat** [comment] 2022-03-04 02:39
Duplicate of https://github.com/soonlabs/soonaverse/issues/173

**Closed by adamkundrat** 2022-03-04 02:39 UTC
Labels: enhancement
