### ISSUE TITLE
Two different addresses for proceeds from sales and royalties for tax reasons

### ISSUE THREAD

**Issue by Peratron** [soonlabs/soonaverse-dao#493] opened 2022-03-26 06:46 UTC
There are countries where revenues from sales and royalties have to be separated for tax reasons. For this it would be necessary to store an additional address in the Space. So it would be good if a space would get two addresses. One for the sales and one for the royalties.

**Comment by adamkundrat** [comment] 2022-03-28 00:16
duplicate of https://github.com/soonlabs/soonaverse-dao/discussions/435 

See more in that discussion and feel free to expand.

**Closed by adamkundrat** 2022-03-28 00:16 UTC
Labels: invalid
