### ISSUE TITLE
Soonaverse-Sort space based on Member Count

### ISSUE THREAD

**Issue by gablucoin** [soonlabs/soonaverse-dao#303] opened 2022-02-23 06:07 UTC
Sort space based on member is a must feature. 
Shouldn't take devs to more than 5 minutes to implement as all the infra is already there.

**Comment by adamkundrat** [comment] 2022-03-04 02:50
duplicate of https://github.com/soonlabs/soonaverse-dao/issues/260

**Comment by adamkundrat** [comment] 2022-03-04 02:50
...and btw it does not take 5 minutes.

**Closed by adamkundrat** 2022-03-04 02:50 UTC
