### ISSUE TITLE
Approving more pending Awards at once

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#222] opened 2021-12-22 07:59 UTC
**Is your feature request related to a problem? Please describe.**
I created badges for 1000 people and have to sign every single one of them to reward them with an award

**Describe the solution you'd like**
It would be great if I could approve many pending awards at once

**Describe alternatives you've considered**
There is no alternative... Otherwise it only makes sense to reward only a few people, because it is too time consuming

**Additional context**
![2021-12-22 08_47_35-Soonaverse - Award](https://user-images.githubusercontent.com/45822157/147056768-4c9578e9-1b6f-47aa-ae85-45acf4441ae8.png)

**Comment by adamkundrat** [comment] 2022-03-04 03:35
Agree, closing as duplicate of https://github.com/soonlabs/soonaverse-dao/discussions/81

**Closed by adamkundrat** 2022-03-04 03:35 UTC
