### ISSUE TITLE
Mark my Spaces with "already a member"

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#174] opened 2021-12-08 09:28 UTC
**Is your feature request related to a problem? Please describe.**
If I check on the list to join new DAOs I don't see if I might already have entered this Space already

**Describe the solution you'd like**
Maybe there could be a checkmark to see that I already have entered this space

**Describe alternatives you've considered**
Or highlight the frame somehow

**Additional context**
![image](https://user-images.githubusercontent.com/45822157/145183646-6603fe12-fc27-4df7-9404-ffadde3b961a.png)

**Comment by nicole-obrien** [comment] 2021-12-08 14:22
Duplicate of https://github.com/soonlabs/soonaverse-dao/issues/139 😸

**Closed** 2021-12-08 17:13 UTC
